name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  main-test:
    needs: [todo-to-issue]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-24.04, ubuntu-22.04, ubuntu-20.04]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        if [[ $RUNNER_OS == 'Linux' ]]; then
          if grep -q '^ID=ubuntu' /etc/os-release; then
            sudo apt-get update || sudo apt-get update || sudo apt-get update
            sudo apt-get install -y xterm ncurses-bin
          else
            echo "Invalid OS for pipeline. Only works with Ubuntu"
            exit 1
          fi
        else
            echo "Invalid OS detected"
            exit 2
        fi

    - name: main test script
      run: |
        bash tests/main_tests

    - name: Create a new version
      if: ${{ success() }}
      run: |
        echo "Creating new version"
        git tag v1.0.${{ github.run_number }} || true
        git push origin --tags || true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  todo-to-issue:
    strategy:
      fail-fast: true
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action@v5"
